Initial commit

diff --git a/.github/workflows/symfony.yml b/.github/workflows/symfony.yml
--- a/.github/workflows/symfony.yml
+++ b/.github/workflows/symfony.yml
@@ -56,13 +56,14 @@ jobs:
         run: composer install --no-progress --prefer-dist --optimize-autoloader
 
       - name: Run Migration
-        run: |
-          php bin/console doctrine:migrations:migrate || echo "No migrations found or migration failed"
+        run: php bin/console d:m:m || echo "No migrations found or migration failed"
         env:
           DATABASE_URL: mysql://root:@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/crm
 
-      - name: Install PHPUnit
-        run: simple-phpunit install
-
       - name: Run tests
-        run: simple-phpunit --coverage-text
+        run: |
+          php bin/console d:m:m || echo "No migrations found or migration failed"
+          php bin/console d:f:l --no-interaction --env=test || echo "No fixtures found or fixtures failed"
+          php bin/phpunit
+        env:
+          DATABASE_URL: mysql://root:@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/crm_test
